#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Handbol.Resource", IsApplication=true)]

namespace Handbol
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int btnGoalAddToLocal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int btnGoalAddToVisitor = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnGoalDecreaseToLocal = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int btnGoalDecreaseToVisitor = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int btnPart1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btnPart2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnPart3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btnPart4 = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int btnResetAll = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int btnTimerPause = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnTimerPlay = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int btnTimerReset = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int chronoHelper = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int gridLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int toggleSound = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int txtResultPart1 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int txtResultPart2 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int txtResultPart3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int txtResultPart4 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int txtResultTotal = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int bad_piu = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bad_trombon = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_windows_error = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int good_applause = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int good_ovacion = 2130968580;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int btnResetAll = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int txtPart = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
