#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Handbol.Resource", IsApplication=true)]

namespace Handbol
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int btnGoalAddToLocal = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btnGoalAddToVisitor = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btnGoalDecreaseToLocal = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int btnGoalDecreaseToVisitor = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int btnPart1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnPart2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnPart3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btnPart4 = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int btnResetAll = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int btnTimerPause = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btnTimerPlay = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int btnTimerReset = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int chronometer = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int txtResultPart1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int txtResultPart2 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int txtResultPart3 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int txtResultPart4 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int txtResultTotal = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int btnResetAll = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int txtPart = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
